name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: install libfltk1.3-dev
      run: sudo apt update && sudo apt install libfltk1.3-dev -y
    - name: make
      run: make
