name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: install libfltk1.3-dev
      run: sudo apt update && sudo apt install libfltk1.3-dev -y
    - name: make
      run: make
    - name: Create Artifact
      run: |
        mkdir release
        cp dlauncher release/dlauncher
    - name: Publish Artifact
      uses: actions/upload-artifact@v2
      with:
        name: web-release
        path: release
